/*
  Generate src/version.ts from package.json
  Usage: node tools/write-version.cjs
*/
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const pkgPath = path.join(root, 'package.json');
const outDirRoot = path.join(root, 'src');
const outFileRoot = path.join(outDirRoot, 'version.ts');
const outDirApp = path.join(root, 'src', 'app');
const outFileApp = path.join(outDirApp, 'version.ts');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

try {
  const pkg = readJson(pkgPath);
  const version = pkg.version || '0.0.0';
  ensureDir(outDirRoot);
  ensureDir(outDirApp);
  const banner = '/* Auto-generated by tools/write-version.cjs — do not edit manually */\n';
  const content = `${banner}export const APP_VERSION = '${version}';\n`;
  fs.writeFileSync(outFileRoot, content, 'utf8');
  fs.writeFileSync(outFileApp, content, 'utf8');
  console.log(`[write-version] Wrote ${path.relative(root, outFileRoot)} and ${path.relative(root, outFileApp)} with version ${version}`);
} catch (err) {
  console.error('[write-version] Failed to write version.ts:', err.message);
  process.exitCode = 1;
}
